# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import services.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_prod', models.AutoField(primary_key=True, serialize=False)),
                ('cod_barras_prod', models.CharField(max_length=20, unique=True)),
                ('nombre_prod', models.CharField(max_length=150)),
                ('costo_prod', models.DecimalField(decimal_places=6, max_digits=12)),
                ('precio1_prod', models.DecimalField(decimal_places=3, max_digits=8)),
                ('precio2_prod', models.DecimalField(decimal_places=3, max_digits=8)),
                ('precio3_prod', models.DecimalField(decimal_places=3, max_digits=8)),
                ('iva_prod', models.IntegerField()),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('cantidad_prod', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidadminima', models.DecimalField(db_column='cantidadMinima', decimal_places=2, max_digits=5)),
                ('cant_xcaja', models.IntegerField(blank=True, db_column='cant_xCaja', null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=services.models.carga_funcion)),
                ('cod_subproducto', models.ForeignKey(blank=True, db_column='cod_subproducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.Producto')),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('pasillo', models.CharField(blank=True, max_length=20, null=True)),
                ('estand', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.Ubicacion'),
        ),
    ]
